name: Validate YAML files

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Validate YAML syntax
      uses: redhat-actions/yaml-validator@v1
      with:
        file_or_dir: .
        recursive: true
        fail_on_error: true
